// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8wL5tNF2-T_w9G9fvUse_hX2UPIOsW3g',
    appId: '1:571180729908:web:118da5e3b6640610c8ac61',
    messagingSenderId: '571180729908',
    projectId: 'atlas-news-68cfe',
    authDomain: 'atlas-news-68cfe.firebaseapp.com',
    storageBucket: 'atlas-news-68cfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1tA4-O3WGI52LURKNb4XidoRx209GpzQ',
    appId: '1:571180729908:android:58ddabaca28b2f3cc8ac61',
    messagingSenderId: '571180729908',
    projectId: 'atlas-news-68cfe',
    storageBucket: 'atlas-news-68cfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kLcVTma1CG0Dt4EA_K-jboMNLkOLt2A',
    appId: '1:571180729908:ios:904a45a99fb0f22ec8ac61',
    messagingSenderId: '571180729908',
    projectId: 'atlas-news-68cfe',
    storageBucket: 'atlas-news-68cfe.appspot.com',
    iosClientId: '571180729908-orhvjmmupu3h6bfclfsqvggcs75j0kks.apps.googleusercontent.com',
    iosBundleId: 'com.example.atlasNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kLcVTma1CG0Dt4EA_K-jboMNLkOLt2A',
    appId: '1:571180729908:ios:7c854a1941159642c8ac61',
    messagingSenderId: '571180729908',
    projectId: 'atlas-news-68cfe',
    storageBucket: 'atlas-news-68cfe.appspot.com',
    iosClientId: '571180729908-fuj4jofqeeqj6563kp67ddtptletdp2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.atlasNews.RunnerTests',
  );
}
